version: '3.7'

# Configuration for Basil testing / development:
services:
    web:
        build: ./dev-web
        restart: always
        volumes:
            - ./build:/usr/share/nginx/html
        ports:
            - "127.0.0.1:8080:80"
        depends_on:
            - basil
    basil:
        build: ./
        volumes:
            - ./test-config:/etc/basil
        depends_on:
            - redis
    redis:
        image: redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis-data:/data

volumes: 
    redis-data: