version: '3.7'

# Configuration for Basil testing / development:
services:
    basil:
        build: ./
        volumes:
            - ./test-config:/etc/basil
        ports:
            - 8080:8500
        depends_on:
            - redis
    redis:
        image: redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis-data:/data

volumes: 
    redis-data: